#181414759 Ft(login with social media) added google and Facebook login functionality
atlp-rwanda/code-ninjas-be pull request #25
Opened 2022-03-15 05:51 UTC by Robertishimwe

#m

2022-03-16 05:04 UTC, itisWasp reviewed
<img width="922" alt="Screen Shot 2022-03-16 at 06 56 52" src="https://user-images.githubusercontent.com/58687698/158520200-f3324b23-94fc-4c7a-93d3-c1a6e2fbb9f2.png">

Can't start the Dev Server Due to GoogleAuth Error to test your changes and there is no clear explanation on how to start and configure the Google Ids or facebook Ids to test the app with the .env file.

2022-03-16 05:19 UTC, Robertishimwe commented
> <img alt="Screen Shot 2022-03-16 at 06 56 52" width="922" src="https://user-images.githubusercontent.com/58687698/158520200-f3324b23-94fc-4c7a-93d3-c1a6e2fbb9f2.png">
> 
> Can't start the Dev Server Due to GoogleAuth Error to test your changes and there is no clear explanation on how to start and configure the Google Ids or facebook Ids to test the app with the .env file.

i have updated `.env.example` file. update your `env` file referring to `env.example`, it will work

2022-03-16 06:09 UTC, itisWasp reviewed
<img width="1004" alt="Screen Shot 2022-03-16 at 08 05 28" src="https://user-images.githubusercontent.com/58687698/158527143-b487b9c6-f168-4a67-ae6c-22ab55145be6.png">

The ABove picture shows the error that is comming in the codes it is saying that res is not defined which is true check the below image.

<img width="730" alt="Screen Shot 2022-03-16 at 08 06 08" src="https://user-images.githubusercontent.com/58687698/158527274-05e168e7-6ede-4960-9a0d-39df66da4279.png">

2022-03-16 07:12 UTC, Robertishimwe commented
> <img alt="Screen Shot 2022-03-16 at 08 05 28" width="1004" src="https://user-images.githubusercontent.com/58687698/158527143-b487b9c6-f168-4a67-ae6c-22ab55145be6.png">
> 
> The ABove picture shows the error that is comming in the codes it is saying that res is not defined which is true check the below image.
> 
> <img alt="Screen Shot 2022-03-16 at 08 06 08" width="730" src="https://user-images.githubusercontent.com/58687698/158527274-05e168e7-6ede-4960-9a0d-39df66da4279.png">

i have declared res. it should work now

2022-03-16 12:14 UTC, itisWasp approved these changes

2022-03-16 16:02 UTC, Procech20 commented on src/controllers/userController.js
> +        if (emailExists)
Can you use services instead of doing the findOne in controllers

2022-03-16 16:03 UTC, Procech20 commented on src/controllers/userController.js
> +passport.use(passport.session())
Remove the console log please!

2022-03-16 16:04 UTC, Procech20 commented on src/database/seeders/20220302143415-demo-user.js
> +const { v4: uuidv4 } = require('uuid');
Remove the 'use strict' as we are using ES6, it is not important

2022-03-16 16:06 UTC, Procech20 commented on src/services/facebookOauth.js
> +const User = models.User
Can you just destructure User from modal instead of doing it like that

2022-03-27 20:25 UTC, ericus123 commented on src/controllers/user.js
> +    // });
Removed unused codes

2022-03-27 20:26 UTC, ericus123 commented on src/services/TokenService.js
> +//   );
remove unused codes

2022-03-27 20:30 UTC, ericus123 commented on src/app.js
> +app.use('/api', userRouter);
why do these routes point to the same endpoint path **"/api"** ?

2022-04-01 17:26 UTC, ericus123 commented on src/swagger/index.js
remove this

2022-04-01 17:28 UTC, ericus123 commented
Your commit is not formatted well and I'm seeing a lot of unnecessary changes in indentation.
Are you using prettier configuration configured for this app?

2022-04-04 11:49 UTC, ericus123 approved these changes

2022-04-04 11:59 UTC, ericus123 requested changes

2022-04-04 11:59 UTC, ericus123 commented on src/app.js
> +app.use('/api', userRouter);
Why userRouter defined twice ?

2022-04-04 14:40 UTC, ericus123 approved these changes

2022-04-04 14:41 UTC, merged