#181414701 ch(Setup unit testing) Setup unit testing with Mocha & chai
atlp-rwanda/code-ninjas-be pull request #30
Opened 2022-03-17 22:05 UTC by Robertishimwe

### What does this PR do?
 Setup unit testing
### Description of Task to be completed?
To ensure the back end has all functionality working as intended. You may use Mocha as the test runner and `chai` and `chai-http` for the unit tests.

### How should this be manually tested?
Get started By Running commands bellow:
  - clone repo
  - switch to [ch-setup-test-181414759](https://github.com/atlp-rwanda/code-ninjas-be/tree/ch-setup-test-181414701) branch
  - ``yarn install``: to install all dependencies
  - Create .env file
  - Set up .env as stated in .env example
  - run `yarn migrate` to set up table
  -  run `yarn seed` to populate table with sample data
  - -run `yarn test` to start unit testing
  
  - After testing completed successfully you will be able to see passed and failed test, and you will be able to see NYC report .

### Any background context you want to provide?
### What are the relevant pivotal tracker stories?
[#181414701](https://www.pivotaltracker.com/story/show/181414701)

2022-03-18 11:52 UTC, ericus123 commented
Rebase from develop

2022-03-21 14:14 UTC, Procech20 approved these changes
LGTM

2022-03-21 16:34 UTC, ericus123 requested changes

2022-03-21 16:34 UTC, ericus123 commented on package.json
> +        "test": "c8 --reporter=text --reporter=lcov ./node_modules/.bin/mocha --timeout 10000 --exit --require @babel/register"
Please make sure you are using the test environment when running tests

2022-03-22 11:34 UTC, itisWasp approved these changes
As I helped to fix the Issues.

2022-03-22 12:29 UTC, ericus123 requested changes

2022-03-22 12:29 UTC, ericus123 commented on .github/workflows/Node.js.yml
> +>>>>>>> 90321a90a9f3e869738f11c9ef50b725598dd432
Why am I seeing these conflicting changes?
Make sure you resolve these.

2022-03-22 12:29 UTC, ericus123 commented on src/database/config/database.js
> +}
Find a better way to do this without hardcoding the environments as you already have them in NODE_ENV ("development","test","production")

2022-03-22 19:59 UTC, ericus123 approved these changes

2022-03-22 20:00 UTC, merged