#181414705 (chore) CI testing with Github actions
atlp-rwanda/code-ninjas-be pull request #31
Opened 2022-03-17 23:33 UTC by niyojuste

### What does this PR do?
 Sets up continuous integration testing
### Description of Task to be completed?
Configure a Github workflow that runs test for every pull request into develop or main branches
### How should this be manually tested?
Get started By Running commands bellow:
  - clone repo
  - checkout to your new branch
  - Add your changes
  - Push to your new remote branch
  - Create a new pull request to develop
  - At the bottom of your pull request it should be running the tests
  - Await to see if the checks pass
 
### Any background context you want to provide?
Configured with coveralls. A badge on the README shall read the coverage of all the tests
### What are the relevant pivotal tracker stories?
[##181414705](https://www.pivotaltracker.com/story/show/181414705)
### Screenshots (if appropriate)
### Questions:

2022-03-18 05:40 UTC, ericus123 reviewed
Add a step for running tests

2022-03-21 07:32 UTC, Procech20 approved these changes
LGTM

2022-03-23 11:32 UTC, Robertishimwe approved these changes

2022-03-23 12:19 UTC, itisWasp requested changes
Please check your codes to many files changed because of formatting please check if you have prettier configured and installed as this will affect us when we are rebasing since all our code base are formatted by prettier.

2022-03-23 13:18 UTC, didasmbalanya requested changes

2022-03-23 13:18 UTC, didasmbalanya commented on test/usertest.spec.js
> +});
This should fail unless for the right users. Look for a dummy endpoint that should not be protected and can test a call to the db. Or do a direct test with the db. Create something and read it

2022-03-23 14:53 UTC, ericus123 commented
Add test script in pre-commit hook

2022-03-24 21:19 UTC, ericus123 commented on test/usertest.spec.js
> +// });
This should be removed

2022-03-24 21:33 UTC, niyojuste commented on test/usertest.spec.js
> +// });
Now removed

2022-03-24 21:37 UTC, ericus123 commented on test/usertest.spec.js
> +// });
Also you can add a CI status badge

2022-03-25 06:26 UTC, ericus123 approved these changes

2022-03-25 06:29 UTC, itisWasp approved these changes

2022-03-25 18:45 UTC, merged