#181414771 feature(comments):Users should be able to give comments
atlp-rwanda/code-ninjas-be pull request #52
Opened 2022-05-08 02:25 UTC by Steve-Ndicunguye

**What does this PR do?**

Provide a user comment

**Description of Task to be completed?**

- Create comment route
- A user should be able to provide give a comment to a travel request
- Test the route
- Document the route

**How should this be manually tested?**

- clone repo
- switch to `ft-comment-181414771` branch
- Run yarn install to install all dependencies
- Set up .env as shown in .env.example
- Use Postman or any other API Testing platform to run the routes

**What to expect after running the commands:**

- A user should be able to comment on a travel request
- Get all comments
- Delete a particular comment

**What are the relevant pivotal tracker stories?**

https://www.pivotaltracker.com/projects/2556266/stories/181414771

**Task implementation plan**

1. Name of task

- Provide comments

2. Pivot Tracker ID

- #181414771

3. Branch Name

- ft-comment-181414771

4. Description of task (Paraphrase what we have in Pivot Tracker)

Comment threads help you keep track of conversations and are necessary for future reference.
As a user or manager, I should be able to post a comment relating to a request made so that the request owner can use the details of the comment for his action or information

5. Acceptance criteria (Checks to be made)

[ User should be able to give a comment ]
Scenario: Given a user makes a travel request in the Barefoot Nomad, after that he can comment out his/her experience.

6. Database schema (Migration & models)

UserId: INTEGER, message: STRING

7. Validations point (Input to validate)

Will use Joi validations to check for any incorrect user input

8. Logic on the access (Explaining who is allowed to CRUD (if applicable) the entities you are working on)

Users will be able to give a comment after making a travel request in the Barefoot Nomad

9. Logic on actual Implementation

Setup comments model
Setup the validations using Joi
Use middleware to check a user's token
Create a comment controller
Create the routes
Test the routes with mocha & chai
Document the endpoint with swagger

10. Endpoints Format:

POST : Post a user comment
GET: To view all comments
DELETE: Delete a comment

2022-05-09 14:12 UTC, Robertishimwe commented
rebase your PR

2022-05-10 08:09 UTC, niyojuste requested changes

2022-05-10 08:09 UTC, niyojuste commented on src/controllers/tripRequestController.js
> +      });
Add the userId parameter to target only the comments by the requesting user

2022-05-10 09:09 UTC, Robertishimwe approved these changes

2022-05-10 09:13 UTC, niyojuste approved these changes

2022-05-10 09:17 UTC, itisWasp approved these changes

2022-05-11 09:45 UTC, merged