#181414778 feature (Chats): Users should be able to chat on Barefoot Nomad
atlp-rwanda/code-ninjas-be pull request #55
Opened 2022-05-12 16:56 UTC by Steve-Ndicunguye

**1. Name of task**
Chat Messages
**2. Pivot Tracker ID**
https://www.pivotaltracker.com/n/projects/2556266/stories/181414778
**3. Branch Name**
ft-chats-181414778
**4. Description of task**
GIVEN the user is online
WHEN they open the chat tab
THEN they should be able to read all of the past chats

GIVEN the user is online
WHEN they open the chat tab
THEN they should be able to post a public chat

GIVEN the user
WHEN they post a chat
THEN it should be able to be echoed to all online users in realtime.
**5. Logic On Actual Implementation**
Create chat messages and retreive all chat messages posted by users logged in Barefoot Nomad

2022-05-17 08:30 UTC, Robertishimwe commented
HOW CAN WE TEST THIS?

2022-05-18 10:48 UTC, Robertishimwe approved these changes
Good job

2022-05-18 11:37 UTC, didasmbalanya requested changes
Good work.  just a few things to look into

2022-05-18 11:37 UTC, didasmbalanya commented on src/database/models/chatmessage.js
> +  ChatMessage.init(
does this automatically add an auto increment ID to this model?

2022-05-18 11:37 UTC, didasmbalanya commented on src/database/models/user.js
> +      });
user and room relationship here?

2022-05-18 11:37 UTC, didasmbalanya commented on test/chat.spec.js
> +//           .send();
why is this commented?

2022-05-18 14:01 UTC, Procech20 reviewed
Please refer to the [PR Template](https://github.com/atlp-rwanda/code-ninjas-be/blob/develop/PR-Template.md) to make the PR description more understandable

2022-05-20 07:06 UTC, ericus123 approved these changes

2022-05-22 12:33 UTC, amani-eric approved these changes

2022-05-22 12:45 UTC, merged